---

# Example of a configuration when using Vultr
vultr:
  api:
    account: ~  # Use "default" by default
    key: ~      # Put your api key here or left it to null to get it from default ansible settings
                # See https://docs.ansible.com/ansible/latest/modules/vultr_account_info_module.html

# Client configuration (homebox)
client:
  domain: mybox.io

# Where to save the VPN configuration for homebox
# By default, it will copy in homebox/backup/<domain>/<vpn-type>/
# with homebox at the same level as homebox-relay
# backup_folder: /tmp/xxxx

# Configuration example
system:
  name: homebox-relay                      # If you are using dynamic inventory, this name should be in your hosts file too.
  vpn: fastd                               # The type of vpn to use. fastd at the moment
  hostname: foxy                           # The host name is not really important, you can put anything you want
  ipv6_enabled: true                       # If you want to use an IPv6 for your box too
  region: London                           # See https://www.vultr.com/features/datacenter-locations/
  os: Debian 10 x64 (buster)               # Perhaps you want to keep this
  plan: 1024 MB RAM,25 GB SSD,1.00 TB BW   # and this too. See Vultr doc to see the possible values
  ssh_keys:                                #
    - name: default                        # these keys will be copied to the /root/.ssh/authorized_keys
      path: /home/andre/.ssh/id_rsa.pub
