---

# This playbooks build a VM on Vultr (https://vultr.com/)
- name: Build a vultr server using the API
  hosts: localhost
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
  roles:
    - role: vultr-vm-provision
